name: Deploy
run-name: Deploy ${{ inputs.version }} to ${{ inputs.environment }} ${{ inputs.region }} by @${{ github.actor }}

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
      region:
        description: 'Region to deploy to'
        required: true
        type: string
      version:
        description: 'Version to deploy'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: environment
      region:
        description: 'Region to deploy to'
        options: ['us-east-1', 'us-west-2']
        required: true
        type: choice
      version:
        description: 'Version to deploy'
        required: true
        type: string

jobs:
  validate:
    name: Validate Image
    runs-on: ubuntu-latest
    
    steps:
    - name: Validate
      run: |
        echo 'Validate: ${{ inputs.version }}'

  plan:
    name: Plan
    needs: validate
    runs-on: ubuntu-latest
    
    steps:
    - name: Plan
      run: |
        echo 'Plan - ${{ inputs.environment }} ${{ inputs.region }}'

  apply:
    environment:
      name: ${{ inputs.environment }}
    name: Apply
    needs: plan
    runs-on: ubuntu-latest
    
    steps:
    - name: Apply
      run: |
        echo 'Apply - ${{ inputs.environment }} ${{ inputs.region }}'
